version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL="postgresql://youruser:yourpassword@my_network:5432/yourdatabase"
      - REDIS_URL=http://localhost:6379
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000' # Adjust if frontend runs on a different port
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:3001 # Use backend service name for inter-container communication
    networks:
      - my_network

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:6
    ports:
      - '6379:6379'
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
