version: '3.8'

services:
  backend:
    image: ghcr.io/satyazzz123/sample-fullstack-application/backend-image:latest
    ports:
      - '3001:3001'
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://youruser:yourpassword@db:5432/yourdatabase
      - REDIS_URL=redis://redis:6379
    networks:
      - my_network
    command: ["/bin/bash", "-c", "/wait-for-it.sh db:5432 --timeout=60 --strict -- npx prisma migrate dev --name init && npx prisma generate && yarn start"]

  frontend:
    image: ghcr.io/satyazzz123/sample-fullstack-application/frontend-image:latest
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=http://backend:3001
    networks:
      - my_network

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:6
    ports:
      - '6379:6379'
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network: