name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     
      - name: Checkout repository
        uses: actions/checkout@v2

     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

     
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets._GITHUB_TOKEN }}

     
      - name: Build frontend Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/frontend-image:latest ./frontend

      - name: Push frontend Docker image
        run: docker push ghcr.io/${{ github.repository }}/frontend-image:latest

      
      - name: Build backend Docker image
        run: docker build -t ghcr.io/${{ github.repository }}/backend-image:latest ./backend

      - name: Push backend Docker image
        run: docker push ghcr.io/${{ github.repository }}/backend-image:latest
